### ISSUE TITLE
Feature/improvement request: allow use of variables in paths for Custom Feedback

### ISSUE THREAD

**Issue by PhillPower** [bitfocus/companion-module-analogway-awj#5]
Similar to 'custom replace command can use variables for path, text entry and object entry', would be very useful for choosing screens and layers to manipulate.

**Comment by dnmeid** [comment]
This would make the feedback dynamic. Everytime the variable changes, the feedback changes. That would not only mean having to recheck if the feedback is true but also the variable which is generated with the feedback would have to be regenerated. There are two possible problems: 1. the module generates a few thousand variables which you don't see. There could be a performance issue if your path variable changes fast. 2. you could program a feedback variable feedback aka a ring reference.

I could do checks for both problems, but I don't feel it is worth the effort. And if one of the problems kicks in, the feedback wouldn't be deterministic any more.
Can you better describe why this feature would be "very useful"?

**Comment by dnmeid** [comment]
All right, so actually you need something to work with the rotaries. So far I did not program anything for the rotaries because it is very likely that the way Companion interacts with rotaries will change.
Maybe your workaround can be achieved if I add an action which does the same as the custom feedback: reading a value from the device and writing it to a variable. Basically a "AWJ get" instead of a "AWJ replace". The difference to the feedback would be that the action is only fired on demand, so I can avoid feedback loops.

**Comment by PhillPower** [comment]
That would be brilliant.

> it is very likely that the way Companion interacts with rotaries will change.

Well, damn.

**Comment by dnmeid** [comment]
Get action is added, should be in betas in a few hours.
